insert into Subject_14 (subject_no, subject_name, subject_units) values (13289, 'Professor', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13159, 'Accounting Assistant I', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13095, 'Financial Analyst', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13061, 'VP Accounting', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13024, 'Senior Financial Analyst', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13258, 'Recruiting Manager', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13203, 'Registered Nurse', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13215, 'Graphic Designer', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13259, 'Desktop Support Technician', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13298, 'Sales Representative', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13289, 'Senior Developer', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13199, 'Safety Technician III', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13302, 'Teacher', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13295, 'Analyst Programmer', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13075, 'General Manager', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13299, 'Accountant III', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13277, 'Teacher', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13148, 'Geological Engineer', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13125, 'Business Systems Development Analyst', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13245, 'Human Resources Manager', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13327, 'Community Outreach Specialist', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13185, 'Cost Accountant', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13091, 'Developer III', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13085, 'Accounting Assistant II', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13082, 'Design Engineer', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13150, 'Teacher', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13284, 'Social Worker', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13283, 'Physical Therapy Assistant', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13270, 'Professor', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13107, 'Programmer Analyst IV', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13249, 'Structural Analysis Engineer', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13202, 'Teacher', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13316, 'Physical Therapy Assistant', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13188, 'Food Chemist', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13166, 'Quality Control Specialist', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13236, 'Senior Sales Associate', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13275, 'VP Product Management', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13211, 'Automation Specialist I', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13217, 'Registered Nurse', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13240, 'Geological Engineer', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13292, 'Mechanical Systems Engineer', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13056, 'Human Resources Manager', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13307, 'Technical Writer', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13265, 'Executive Secretary', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13290, 'Sales Representative', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13191, 'Teacher', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13008, 'Editor', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13233, 'Research Nurse', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13238, 'Account Representative I', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13108, 'Structural Analysis Engineer', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13147, 'VP Marketing', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13128, 'Office Assistant III', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13112, 'Mechanical Systems Engineer', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13268, 'Automation Specialist II', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13187, 'Librarian', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13212, 'Help Desk Technician', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13204, 'Tax Accountant', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13005, 'Mechanical Systems Engineer', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13009, 'Chemical Engineer', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13121, 'Research Associate', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13057, 'Sales Representative', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13028, 'Mechanical Systems Engineer', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13158, 'Developer IV', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13299, 'Help Desk Technician', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13159, 'Safety Technician IV', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13087, 'VP Accounting', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13194, 'Community Outreach Specialist', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13328, 'Software Consultant', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13301, 'Chemical Engineer', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13194, 'Chief Design Engineer', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13031, 'Mechanical Systems Engineer', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13281, 'Nurse', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13278, 'VP Sales', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13267, 'Research Assistant III', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13325, 'Dental Hygienist', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13132, 'Assistant Manager', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13088, 'Senior Developer', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13329, 'Budget/Accounting Analyst II', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13232, 'Research Nurse', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13064, 'Internal Auditor', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13141, 'Business Systems Development Analyst', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13044, 'Analog Circuit Design manager', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13047, 'Account Executive', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13283, 'Financial Analyst', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13283, 'Product Engineer', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13206, 'Analyst Programmer', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13142, 'Geological Engineer', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13083, 'Executive Secretary', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13289, 'Sales Representative', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13143, 'Registered Nurse', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13013, 'Senior Cost Accountant', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13183, 'Assistant Manager', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13279, 'Product Engineer', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13232, 'Statistician IV', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13280, 'Sales Associate', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13308, 'Clinical Specialist', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13309, 'Web Designer I', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13241, 'Civil Engineer', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13059, 'Civil Engineer', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13068, 'Accountant III', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13290, 'Senior Cost Accountant', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13200, 'Clinical Specialist', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13197, 'Research Assistant III', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13120, 'Research Nurse', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13205, 'Web Developer II', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13266, 'Paralegal', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13299, 'Chief Design Engineer', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13007, 'Community Outreach Specialist', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13322, 'Internal Auditor', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13240, 'Teacher', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13086, 'Financial Advisor', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13270, 'Graphic Designer', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13162, 'Quality Engineer', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13125, 'Web Developer IV', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13125, 'Statistician IV', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13190, 'Paralegal', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13008, 'Statistician IV', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13062, 'Analyst Programmer', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13077, 'Analyst Programmer', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13020, 'Graphic Designer', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13072, 'Electrical Engineer', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13067, 'Dental Hygienist', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13201, 'Help Desk Operator', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13169, 'Nurse', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13302, 'Help Desk Technician', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13180, 'Geological Engineer', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13275, 'Project Manager', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13240, 'Electrical Engineer', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13300, 'Actuary', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13307, 'Senior Financial Analyst', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13085, 'Compensation Analyst', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13120, 'Developer II', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13203, 'Chemical Engineer', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13015, 'Media Manager I', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13107, 'Quality Control Specialist', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13056, 'Community Outreach Specialist', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13241, 'Help Desk Technician', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13032, 'General Manager', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13064, 'Senior Editor', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13293, 'Health Coach II', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13191, 'Geological Engineer', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13129, 'Administrative Officer', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13189, 'Design Engineer', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13016, 'VP Marketing', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13053, 'Payment Adjustment Coordinator', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13202, 'Analyst Programmer', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13063, 'Web Designer I', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13233, 'Senior Quality Engineer', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13326, 'Media Manager IV', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13085, 'Research Nurse', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13242, 'Environmental Tech', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13038, 'Teacher', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13164, 'Social Worker', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13028, 'Senior Cost Accountant', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13330, 'Biostatistician IV', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13101, 'Structural Analysis Engineer', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13023, 'Quality Engineer', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13311, 'Research Associate', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13103, 'Research Nurse', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13147, 'VP Quality Control', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13011, 'Senior Cost Accountant', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13255, 'Internal Auditor', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13222, 'Data Coordiator', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13121, 'Statistician IV', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13246, 'Desktop Support Technician', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13308, 'Human Resources Manager', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13176, 'Information Systems Manager', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13251, 'Data Coordiator', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13280, 'Geologist IV', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13103, 'Internal Auditor', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13271, 'Assistant Manager', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13330, 'Project Manager', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13078, 'Social Worker', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13067, 'Director of Sales', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13310, 'Payment Adjustment Coordinator', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13244, 'Mechanical Systems Engineer', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13078, 'Cost Accountant', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13103, 'Financial Advisor', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13080, 'Senior Quality Engineer', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13020, 'Information Systems Manager', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13141, 'Speech Pathologist', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13134, 'Automation Specialist I', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13077, 'Associate Professor', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13001, 'Systems Administrator III', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13034, 'Financial Advisor', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13184, 'Paralegal', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13021, 'Registered Nurse', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13243, 'Mechanical Systems Engineer', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13124, 'Systems Administrator I', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13191, 'Staff Scientist', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13192, 'Help Desk Technician', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13001, 'Executive Secretary', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13232, 'Professor', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13103, 'Help Desk Technician', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13130, 'Actuary', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13088, 'Senior Quality Engineer', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13098, 'Statistician II', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13311, 'Geologist III', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13124, 'Structural Engineer', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13266, 'VP Product Management', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13127, 'Technical Writer', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13018, 'Assistant Media Planner', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13255, 'Teacher', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13046, 'Accounting Assistant IV', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13079, 'Research Assistant III', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13151, 'Assistant Media Planner', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13134, 'Administrative Officer', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13215, 'Software Consultant', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13091, 'VP Product Management', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13070, 'Assistant Media Planner', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13294, 'Staff Accountant I', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13070, 'Product Engineer', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13090, 'Dental Hygienist', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13290, 'Senior Sales Associate', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13045, 'Developer I', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13069, 'Editor', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13178, 'Cost Accountant', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13110, 'Geological Engineer', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13108, 'Accounting Assistant I', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13162, 'Web Designer IV', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13332, 'Sales Associate', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13264, 'Product Engineer', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13236, 'Senior Editor', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13198, 'Database Administrator IV', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13073, 'Dental Hygienist', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13292, 'Programmer II', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13078, 'Database Administrator III', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13053, 'Web Designer II', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13274, 'Assistant Media Planner', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13038, 'Database Administrator III', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13238, 'Structural Engineer', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13020, 'Director of Sales', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13154, 'Developer I', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13224, 'Automation Specialist II', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13073, 'Account Executive', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13021, 'Product Engineer', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13143, 'Web Designer II', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13316, 'VP Quality Control', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13037, 'Product Engineer', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13219, 'Design Engineer', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13135, 'Chemical Engineer', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13155, 'Help Desk Technician', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13028, 'Operator', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13084, 'Research Assistant IV', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13322, 'Programmer IV', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13275, 'Social Worker', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13050, 'Physical Therapy Assistant', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13032, 'Paralegal', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13325, 'Assistant Manager', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13034, 'Marketing Assistant', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13231, 'GIS Technical Architect', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13092, 'Staff Accountant III', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13237, 'Financial Advisor', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13146, 'Help Desk Operator', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13255, 'Structural Analysis Engineer', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13141, 'Recruiting Manager', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13209, 'Chemical Engineer', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13298, 'Compensation Analyst', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13249, 'Account Executive', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13259, 'Clinical Specialist', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13275, 'Registered Nurse', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13032, 'Sales Representative', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13020, 'Pharmacist', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13316, 'Geological Engineer', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13112, 'Administrative Officer', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13031, 'Business Systems Development Analyst', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13098, 'Staff Scientist', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13294, 'Mechanical Systems Engineer', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13079, 'Librarian', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13277, 'Administrative Officer', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13259, 'Web Developer IV', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13067, 'Legal Assistant', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13283, 'Software Consultant', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13281, 'Research Nurse', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13307, 'Research Associate', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13022, 'Biostatistician III', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13066, 'Food Chemist', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13219, 'Editor', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13060, 'Help Desk Operator', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13001, 'Geological Engineer', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13067, 'Food Chemist', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13148, 'Civil Engineer', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13156, 'Research Associate', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13077, 'Senior Developer', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13165, 'Biostatistician I', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13160, 'Account Executive', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13180, 'Office Assistant I', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13238, 'Account Executive', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13061, 'Design Engineer', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13303, 'Nurse Practicioner', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13329, 'Recruiter', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13099, 'Payment Adjustment Coordinator', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13209, 'Payment Adjustment Coordinator', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13143, 'Compensation Analyst', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13003, 'Help Desk Technician', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13308, 'Help Desk Technician', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13220, 'Registered Nurse', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13097, 'VP Product Management', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13121, 'Developer II', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13262, 'Financial Advisor', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13301, 'Quality Control Specialist', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13094, 'Financial Analyst', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13007, 'Software Engineer III', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13172, 'Assistant Manager', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13040, 'Dental Hygienist', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13018, 'Paralegal', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13109, 'Information Systems Manager', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13075, 'Nurse', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13125, 'Administrative Assistant II', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13104, 'Operator', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13020, 'Database Administrator I', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13318, 'Account Representative I', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13010, 'Paralegal', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13081, 'Senior Sales Associate', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13090, 'Account Executive', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13275, 'VP Product Management', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13146, 'Design Engineer', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13239, 'Editor', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13016, 'Tax Accountant', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13231, 'Speech Pathologist', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13286, 'Geological Engineer', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13225, 'Accounting Assistant IV', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13170, 'Budget/Accounting Analyst III', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13094, 'Data Coordiator', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13146, 'Legal Assistant', 2);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13317, 'Programmer I', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13309, 'Software Test Engineer II', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13328, 'Internal Auditor', 4);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13120, 'Environmental Tech', 0);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13300, 'Automation Specialist II', 1);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13139, 'VP Accounting', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13038, 'Associate Professor', 3);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13116, 'Recruiting Manager', 5);
insert into Subject_14 (subject_no, subject_name, subject_units) values (13125, 'Cost Accountant', 1);
